version: '2'

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_USER: 'yes'
    ports:
      - ${DB_PORT:-0}:3306
    volumes:
      - my-db:/var/lib/mysql
  cache:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
    - "${REDIS_PORT:-0}:6379"
  app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '${WEB_PORT:-0}:8000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-0}
      - DB_USERNAME=${DB_USER}
      - DB_DATABASE=${DB_NAME}
    volumes:
      - './project:/app'
    depends_on:
      - db
volumes:
  my-db:
  cache:
    driver: local
