version: "3.7"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_USER: 'yes'
    ports:
      - '${DB_PORT:-0}:3306'
    volumes:
      - my-db:/var/lib/mysql
  app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '${WEB_PORT:-0}:8000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-0}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - '.:/app'
    depends_on:
      - db
volumes:
  my-db:
  cache:
    driver: local
