# # Use root/example as user/password credentials
# version: '3.7'

# services:
#   cache:
#     container_name: redis
#     image: redis:alpine
#     ports:
#     - "${REDIS_PORT:-0}:6379"
#   database:
#     image: mysql:8.0
#     command: mysqld --default-authentication-plugin=mysql_native_password
#     environment:
#       - MYSQL_DATABASE=${DB_DATABASE}
#       - MYSQL_USER=${DB_USERNAME}
#       - MYSQL_PASSWORD=${DB_PASSWORD}
#       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#     ports:
#       - 3306:3306
#     volumes:
#       - mysql-data:/var/lib/mysql
# volumes:
#   my-db:
#   cache:
#     drivr: local

version: '3'
services:
  db:
    image: mysql:8
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT-0}:3306'

