version: '3.7'

services:
    app:
        image: wordpress
        restart: always
        ports:
            - '${WEB_PORT:-0}:80'
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        volumes:
            - '.:/var/www/html'
    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_USER=${WORDPRESS_DB_USER}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DB_PORT:-0}:80'
        volumes:
            - db:/var/lib/mysql

volumes:
    app:
    db:
