version: '3.7'

services:
    app:
        image: wordpress
        restart: always
        ports:
            - '${WEB_PORT:-0}:80'
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=${DB_USERNAME}
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
            - WORDPRESS_DB_NAME=${DB_DATABASE}
        volumes:
            - '.:/var/www/html'
    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DB_PORT:-0}:80'
        volumes:
            - db:/var/lib/mysql

volumes:
    app:
    db:
